#!/usr/bin/env python3
"""make_manifest.py - write pam.manifest, the file the COD1.6X client reads for its
"INSTALL / UPDATE PAM" button (menu, Files tab). One line per pk3 the mod folder must hold.

    python3 tools/make_manifest.py <dir> --url <base-url> [--mod __rPAMv115b5] [--version N]
                                   [--remove old.pk3 ...] [-o pam.manifest]

<dir>       the pk3s a SERVER runs (a copy of its __rPAMv115b5/): every *.pk3 in it, no
            subfolders, .bak/.tmp/.new ignored. Generating from the server's own folder is
            what makes the client's copies pass sv_pure byte for byte.
--url       where the same files are downloadable, "<name>" appended. For a GitHub release:
            https://github.com/cod1plus/cod1pluspam/releases/download/<tag>/
--remove    pk3 names the client should delete (previous revisions left in the folder).

Format (parsed by src/features/pam_install.cpp in the client):
    mod <folder>
    version <n>
    file <name> <bytes> <sha256> <url>
    remove <name>
Commit the result at the repo root; the client fetches
https://raw.githubusercontent.com/cod1plus/cod1pluspam/main/pam.manifest
"""
import argparse
import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def default_version():
    try:
        for line in open(os.path.join(HERE, "..", "VERSION"), encoding="ascii"):
            line = line.split("#", 1)[0].strip()
            if line.startswith("EXT_VER="):
                return int(line.split("=", 1)[1].strip())
    except (OSError, ValueError):
        pass
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("dir")
    ap.add_argument("--url", required=True, help="base URL, <name> is appended")
    ap.add_argument("--mod", default="__rPAMv115b5")
    ap.add_argument("--version", type=int, default=default_version())
    ap.add_argument("--remove", nargs="*", default=[])
    ap.add_argument("-o", "--out", default=os.path.join(HERE, "..", "pam.manifest"))
    a = ap.parse_args()

    base = a.url if a.url.endswith("/") else a.url + "/"
    names = sorted(n for n in os.listdir(a.dir)
                   if n.lower().endswith(".pk3") and os.path.isfile(os.path.join(a.dir, n)))
    if not names:
        print("no .pk3 in %s" % a.dir, file=sys.stderr)
        return 1
    lines = ["# cod1plus PAM install manifest - generated by tools/make_manifest.py, do not edit by hand",
             "mod %s" % a.mod, "version %d" % a.version]
    total = 0
    for n in names:
        p = os.path.join(a.dir, n)
        size = os.path.getsize(p)
        total += size
        lines.append("file %s %d %s %s%s" % (n, size, sha256(p), base, n))
    for n in a.remove:
        lines.append("remove %s" % n)
    with open(a.out, "w", encoding="ascii", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("%s: %d file(s), %.1f MB, mod %s v%d" % (a.out, len(names), total / 1048576, a.mod, a.version))
    return 0


if __name__ == "__main__":
    sys.exit(main())
